

runtime: python39
entrypoint: daphne -b :$PORT drowsiness_detection_project.drowsiness_detection_project.asgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "drowisness_detection_project.drowsiness_detection_project.settings"
  PYTHONPATH: "/app/drowsiness_detection_project"
  SECRET_KEY: 'django-insecure-u@#-(r96itdxydn(62-4*-!o$pe(3fg*#ncnyf2exsq_%78d)w'
  DEBUG: 'False'

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

# Add any additional environment variables here
# For example:
# SECRET_KEY: "your-secret-key-here"
# DEBUG: "False"