runtime: python39
entrypoint: daphne -b 0.0.0.0 -p $PORT drowsiness_detection_project.asgi:application
instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: "drowsiness_detection_project.settings"
  SECRET_KEY: 'django-insecure-u@#-(r96itdxydn(62-4*-!o$pe(3fg*#ncnyf2exsq_%78d)w'
  DEBUG: 'False'

  
handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

# Ensure WebSocket connections are handled
network:
  session_affinity: true